### ISSUE TITLE
후원자데이터- 검색

### ISSUE THREAD

**Issue by boazseong** [GiveYouMe/GymAccount#10]
후원자데이터- 검색

없는 코드 혹은 후원자 이름 검색시 결과

MA : 리스트에 아무 회원도 보이지 않음
GA : 지난 번 검색 결과 그대로 보여줌
--> 개선할 수 있다면,  '일치하는 회원이 없음' 팝업창이 뜨면 좋겠음.

**Comment by techcap** [comment]
v0.1.5에서 재현이 안됩니다. 확인 부탁 드립니다.

**Comment by boazseong** [comment]
검색후 지난 번 검색 결과 보여주던 것을 사라졌음.
회원코드, 후원자명 목록은 개선할 것이 없으나, 상세 정보를 보여주는 오른쪽 창의 대부분이 null  값으로 표시되나 일부 ( 분류1, 분류2, 비용부담, 후원자가 지원하는 계정 등록 ) 부분이  null 값이 아닌 이전 데이터의 값이 그대로 남아 있음.

**Comment by techcap** [comment]
구체적인 재현스탭 정보 부탁 드립니다.

**Comment by boazseong** [comment]
답이 너무 늦어 죄송합니다. 

1. 검색창에 "새중앙교회"로 검색한다. 결과값이 나온다. 검색된 회원중 하나를 선택하여 세부 정보를 본다.
2. 검색창에 "새중앙교화"로 '회'가 아닌 '화'로 입력하면 대상이 없기에 모두 null 값인 창을 보여줘야 한다. 
3. 그런데 GA는 일부 필드가 이전에 선택했던 데이터를 보여준다.
분류1, 분류2는 음영으로 보여주어 이것이 디폴트 값을 보여주는 것인지 이전에 보았던 데이터의 값을 보여주는 것인지 명확하지 않음. /
후원자가 지원하는 계정정보,/ 정기간행물의 비용부담 정보  가 이전 회원의 데이터가 남아 있음. 

![2-001](https://user-images.githubusercontent.com/80180034/112918650-51b9d600-9140-11eb-86b1-016c16d660a1.PNG)
![2-002](https://user-images.githubusercontent.com/80180034/112918654-554d5d00-9140-11eb-922e-7d38e1758fa2.PNG)

**Comment by techcap** [comment]
v0.1.7에 반영

**Comment by boazseong** [comment]
확인!
