### ISSUE TITLE
후원자데이터 - 상세검색

### ISSUE THREAD

**Issue by boazseong** [GiveYouMe/GymAccount#11]
후원자데이터 - 상세검색

MA : 후원자명 뿐 아니라 모든 필드에 대하여 일치하는 혹은 포함하는 회원을 모두 보여줌

GA : 후원자명 만 대조하여 일치, 포함하는 결과를 보여줌 

주가 점검 필요 
1. 보여주는 결과 데이터 필드 : 코드, 후원자명만
2. 보여주는 순서 : 코드 올림차순
3. 일치하는 데이터 없을 시 : 결과창에 아무도 보여주지 않음 --> 개선할 수 있다면, 팝업 "해당 회원 없음"

**Comment by techcap** [comment]
v0.1.6에서 수정

**Comment by boazseong** [comment]
확인
