### ISSUE TITLE
후원자데이터 - 분류설정

### ISSUE THREAD

**Issue by boazseong** [GiveYouMe/GymAccount#14]
후원자데이터 - 분류설정

분류설정 버튼 클릭시 팝업창이 뜨게 되어 있으나, GA에서는 동작 없음.
![1-0010-1](https://user-images.githubusercontent.com/80180034/110262710-d7da7500-7ff7-11eb-97bf-0148fa6fd73d.PNG)

![1-0010](https://user-images.githubusercontent.com/80180034/110262665-b9747980-7ff7-11eb-9adf-66f7d0f67563.PNG)

**Comment by techcap** [comment]
v0.1.8에 반영

**Comment by boazseong** [comment]
확인!

**Comment by boazseong** [comment]
팝업창에서 
MA : 분류 1,   분류 2
GA : A | B | C |  ,    A | B | C |  로 나옴

MA  처럼 나오게 요청

**Comment by seungkwanwoo** [comment]
v0.1.10에 반영 되었습니다.

**Comment by boazseong** [comment]
확인!
