### ISSUE TITLE
후원자 데이터 - 인쇄

### ISSUE THREAD

**Issue by boazseong** [GiveYouMe/GymAccount#15]
후원자 데이터 - 인쇄

![1-0010-1](https://user-images.githubusercontent.com/80180034/110283127-eb4f0580-8022-11eb-9feb-070d6051ef20.PNG)
인쇄 선택시 팝업창에서

MA
![1-0011-1](https://user-images.githubusercontent.com/80180034/110283176-fbff7b80-8022-11eb-9c75-f299a8b1bca5.PNG)
GA
![1-0011](https://user-images.githubusercontent.com/80180034/110283180-fc981200-8022-11eb-8910-81c1a18d994f.PNG)
1. 예로 사용된 '귀하' 데이터의 출력 위치가 반대로 되어 있음.
2. <== 오른쪽의 글씨가 끝까지 출력되지 않음. --> 할 수 있다면 가림 없이 모두 출력되도록

**Comment by techcap** [comment]
MA와 GA가 같은 후원자를 선택한게 맞나요?

**Comment by techcap** [comment]
글자 잘리는 문제는 v0.1.8에 반영

**Comment by boazseong** [comment]
확인!
