### ISSUE TITLE
후원자데이터 - 후원내역보기

### ISSUE THREAD

**Issue by boazseong** [GiveYouMe/GymAccount#17]
후원자데이터 - 후원내역보기
![1-0013](https://user-images.githubusercontent.com/80180034/110284410-205c5780-8025-11eb-82c7-9157949db404.PNG)

버튼 클릭시 반응 없음 --> 아래와 같이 팝업 창이 떠야 함.
![1-0013-1](https://user-images.githubusercontent.com/80180034/110284460-31a56400-8025-11eb-9cb3-11907f535d4c.PNG)

**Comment by techcap** [comment]
v0.1.9에 반영

**Comment by boazseong** [comment]
확인!

**Comment by boazseong** [comment]
팝업창 기능 확인 필요
