### ISSUE TITLE
계정별 후원자 - email & send조건

### ISSUE THREAD

**Issue by boazseong** [GiveYouMe/GymAccount#20]
계정별 후원자 - email & send조건
![1-0015-1](https://user-images.githubusercontent.com/80180034/110286084-a1b4e980-8027-11eb-991a-63c8ae133de2.PNG)

글자 짤림, 
계정별 후원자 - email & send조_**건**_

**Comment by seungkwanwoo** [comment]
v0.1.10에 반영. 메일 발송은 지원하지 않는 기능입니다.

**Comment by boazseong** [comment]
사용자 모임에서 2.0버전에 반영하는 것으로 이해하였습니다. 
1.0버전에는 반영하지 않는 것으로 정리하였다고 이해합니다. 

감사합니다.
