### ISSUE TITLE
계정별 후원자 - 소봉투인쇄

### ISSUE THREAD

**Issue by boazseong** [GiveYouMe/GymAccount#21]
계정별 후원자 - 소봉투인쇄
![1-0016](https://user-images.githubusercontent.com/80180034/110287239-7f23d000-8029-11eb-9f6c-de1298aadff3.PNG)

1. 지원하지 않음 안내 
인쇄
인쇄(90도회전) 
선택시 팝업으로 '지원하지 않음' 안내

2. 인쇄 관련 버튼 우측 설정 버튼인 상자안 s 버튼 클릭시 반응 없음 --> 
위의 것은 '소봉투 인쇄 설정'창으로 연결
아래 것은 '소봉투 인쇄 90회전 설정' 창으로 연결 되어야 함.

**Comment by seungkwanwoo** [comment]
v0.1.10에 반영. 인쇄 기능은 "지원하지 않는 기능입니다"는 메시지를 출력합니다.

**Comment by boazseong** [comment]
확인!
