### ISSUE TITLE
계정별 후원자 - 후원자List인쇄, 선교사에게 메일 발송/저장

### ISSUE THREAD

**Issue by boazseong** [GiveYouMe/GymAccount#22]
계정별 후원자 - 후원자List인쇄, 선교사에게 메일 발송/저장

![1-0017-1](https://user-images.githubusercontent.com/80180034/110288982-20138a80-802c-11eb-9762-2cf8162a4584.PNG)
1. 라디오버튼 인쇄 선택후 [확인] 버튼 클릭시 반응 없음 -> 팝업 '지원하지 않음'
2. 라디오 버튼 '엑셀파일로저장(메일발송) 선택후 [확인]버튼 클릭시 반응없음 --> 아래 팝업창 호출
![1-0017-2](https://user-images.githubusercontent.com/80180034/110289187-6a950700-802c-11eb-9772-eb960b972246.PNG)
예 선택시 아래 팝업창 호출 / 아니오 호출시 마지막 팝업창 호출
![1-0017-4](https://user-images.githubusercontent.com/80180034/110289232-7b457d00-802c-11eb-9600-4e8f9137be9e.PNG)
확인 선택시 아래 팝업창 호출
![1-0017-3](https://user-images.githubusercontent.com/80180034/110289272-8b5d5c80-802c-11eb-9a2d-f156dc0e9b2d.PNG)
예 선택시 해당 폴더 탐색기 창 열림 / 아니오 선택시 기존 창으로 복귀
3. 라디오 버튼 'HTM파일로 저장(메일발송) 선택후 [확인]버튼 클릭시 반응없음 --> 파업 '지원하지 않음'

4. 라디오 버튼 3개 동작한 후 선교사에게 메일로 저장된 파일을 보낼 것인지는 라디오 버튼 위에 있는 선택 상자로 결정함. 이 선택상자가 선택된 상태에서 아래 라디오 버튼을 추가로 고르고 [확인]을 누르면, 우선 라디오 버튼 선택된 동작을 수행하고, 그 후에 외부 메일 프로그램을 호출하여 해당 선교사 계정에 등록된 메일 주소로 메일을 보내며 출력한 파일을 첨부함
이 동작을 위해 네모 선택 버튼 선택시 반응 없음 --> 외부 메일 관리 프로그램 호출 (썬더보드, 아웃룩익스프레스)
만일 메일 관리 프로그램이 설치되어 있지 않다면 아래 팝업 창 나와야함. 
![1-0017](https://user-images.githubusercontent.com/80180034/110289826-530a4e00-802d-11eb-8092-4a741f3dcf6d.PNG)

**Comment by seungkwanwoo** [comment]
v0.1.10에 반영. 인쇄, 메일발송 기능은 "지원하지 않는 기능입니다"는 메시지를 출력합니다.
