### ISSUE TITLE
후원자 데이터 - 인쇄 3

### ISSUE THREAD

**Issue by boazseong** [GiveYouMe/GymAccount#23]
후원자 데이터 - 인쇄 3
![1-0018](https://user-images.githubusercontent.com/80180034/110291084-dbd5b980-802e-11eb-8527-6a84ae3bbe72.PNG)

인쇄 선택시 지원하지 않음 팝업 --> 실제 작동해야 함 GA 2.0에서

**Comment by seungkwanwoo** [comment]
v0.1.10에 반영. 인쇄 기능은 "지원하지 않는 기능입니다"는 메시지를 출력합니다.
