### ISSUE TITLE
후원회원조회및인쇄 - 기간 설정 창 일부 보임

### ISSUE THREAD

**Issue by boazseong** [GiveYouMe/GymAccount#26]
후원회원조회및인쇄 - 기간 설정 창 일부 보임

![0001-2](https://user-images.githubusercontent.com/80180034/110894247-df24ba00-833a-11eb-9dd9-523e62fd0ff1.PNG)

기간 입력하는 창과 아래 화살표로 날짜를 클릭해 선택하는 단추 사이에 약간의 감춰져야할 창이 보임.

**Comment by seungkwanwoo** [comment]
v0.1.11에 반영
