### ISSUE TITLE
후원회원조회및인쇄 - 조회시 데이터 결과 오류

### ISSUE THREAD

**Issue by boazseong** [GiveYouMe/GymAccount#27]
후원회원조회및인쇄 - 조회시 데이터 결과 오류

기간을 설정하고 조회 버튼을 누르면 아래와 같이 오류 팝업 창 발생
![0001-1](https://user-images.githubusercontent.com/80180034/110894453-42aee780-833b-11eb-8e17-99612eed40b1.PNG)

--> 조회하여 결과를 보여주어야 함.

**Comment by seungkwanwoo** [comment]
v0.1.11에 반영
