### ISSUE TITLE
후원회원조회및인쇄 - 호칭설정부 오타

### ISSUE THREAD

**Issue by boazseong** [GiveYouMe/GymAccount#29]
후원회원조회및인쇄 - 호칭설정부 오타
![0002](https://user-images.githubusercontent.com/80180034/110894621-8570bf80-833b-11eb-8f4a-889edca42a0d.PNG)
<== 기본값 : 보이는대**로**

**Comment by boazseong** [comment]
후원회원조회및인쇄 - 호칭설정부 오타
![0002](https://user-images.githubusercontent.com/80180034/110894621-8570bf80-833b-11eb-8f4a-889edca42a0d.PNG)
<== 기본값 : 보이는대**### 로**

**Comment by seungkwanwoo** [comment]
v0.1.11에 반영
