### ISSUE TITLE
후원자관련-후원자데이터 열린창내 후원 명단 중 일부 사라짐, 

### ISSUE THREAD

**Issue by boazseong** [GiveYouMe/GymAccount#3]
후원자관련-후원자데이터 

1. 열린 창에서 
코드 | 후원자명 란에 일부 후원자가 보이지 않습니다. 
예를 들어 저희 기관의 경우 010001- 010033번까지 보이지 않고, 0100034번부터 보입니다. 
그래서 ID/후원자 검색란에 코드로 검색하면 나타납니다. 
이때, 해당 후원자를 선택하면 우측의 정보가 변하지 않습니다.

**Comment by techcap** [comment]
010001-010033이 안보이는 이유는 정렬이 안되어 있어서 그렇습니다. 코드 순으로 정렬해서 보여주는 것이 나을까요?

**Comment by boazseong** [comment]
네 기본으로 코드로 정렬이 익숙합니다

**Comment by techcap** [comment]
검색 버그 수정했습니다. v0.1.3

**Comment by boazseong** [comment]
확인!
