### ISSUE TITLE
후원회원조회및인쇄 - 조회옵션 오타

### ISSUE THREAD

**Issue by boazseong** [GiveYouMe/GymAccount#31]
후원회원조회및인쇄 - 조회옵션 오타
![0004](https://user-images.githubusercontent.com/80180034/110895437-1d22dd80-833d-11eb-8ad2-3b3e3ed4ee19.PNG)

전체 밑의 교 --> 교회

**Comment by seungkwanwoo** [comment]
v0.1.11에 반영
