### ISSUE TITLE
후원회원조회및인쇄 - 고급조회옵션 필드명

### ISSUE THREAD

**Issue by boazseong** [GiveYouMe/GymAccount#32]
후원회원조회및인쇄 - 고급조회옵션 필드명

![0005-1](https://user-images.githubusercontent.com/80180034/110895509-3fb4f680-833d-11eb-85a2-9777f58557ed.PNG)
![0005-2](https://user-images.githubusercontent.com/80180034/110895520-43e11400-833d-11eb-8450-da4eee45094c.PNG)

**Comment by seungkwanwoo** [comment]
SQL을 직접 표현하는 것은 보안상 문제가 될 수 있으며, 고급 조회 기능은 GA에서 제외하려고 합니다.
추가적으로 개선이 필요한 사항이 있으면, 취합하여 정리하면 좋겠습니다.

**Comment by boazseong** [comment]
네. 현재는 사용하는 기관이 없는 것으로 알고 있습니다. 

그러난, 후원자 관리와 재정 개발 부분에서 필요한 기능이 있기는 합니다. 기존 기능 안정화 후 다시 다루는 것이 좋겠습니다.

**Comment by seungkwanwoo** [comment]
네. 알겠습니다. 말씀 하신 대로 안정화 이후에 개선이 필요한 내용은 정리하여 진행하면 좋겠습니다. 감사합니다.
