### ISSUE TITLE
후원회원조회및인쇄 - 인쇄선택 오타

### ISSUE THREAD

**Issue by boazseong** [GiveYouMe/GymAccount#33]
후원회원조회및인쇄 - 인쇄선택 오타

![0006-1](https://user-images.githubusercontent.com/80180034/110895586-65420000-833d-11eb-8830-56ed2a587400.PNG)
![0006-2](https://user-images.githubusercontent.com/80180034/110895597-68d58700-833d-11eb-80c7-4c32edadd1d4.PNG)

1. 지로(공 --> 지로(공란)

2. 라벨1 인 -> 라벨1 인쇄

**Comment by seungkwanwoo** [comment]
인쇄 선택 부분은 제외하여 표시 예정입니다.
