### ISSUE TITLE
후원회원조회및인쇄 - 인쇄 관련부

### ISSUE THREAD

**Issue by boazseong** [GiveYouMe/GymAccount#34]
후원회원조회및인쇄 - 인쇄 관련부

버그 : 가장 밑의 인쇄선택 부분의 모든 단추 즐 (s) 나 [인쇄버튼}등을 클릭하면 --> "지원하지 않음" 팝업 도출

향후 기능 : 
1. (s) 선택하면 각 해당 인쇄 설정 으로 이동

**Comment by seungkwanwoo** [comment]
인쇄 관련 부분은 제외하여 표시 예정입니다.
