### ISSUE TITLE
기초정보-환경설정-관리자외 사용자정보

### ISSUE THREAD

**Issue by boazseong** [GiveYouMe/GymAccount#35]
기초정보-환경설정-관리자외 사용자정보

MA
![0007-2](https://user-images.githubusercontent.com/80180034/110896376-cae2bc00-833e-11eb-94b7-33db471d30aa.PNG)
![0007-3](https://user-images.githubusercontent.com/80180034/110896379-cc13e900-833e-11eb-93b7-1fdf61a51eb0.PNG)

GA
![0007-1](https://user-images.githubusercontent.com/80180034/110896368-c6b69e80-833e-11eb-8f06-9da661cf4fef.PNG)

1. 사용자 정보 영역의 어떤 셀에 커서가 있든지 [탭]키를 누르면 그 위쪽의 관리자 작업 영역의 관리자 명 입력란으로 포인터가 이동함  ->> 사용자 정보 영역의 다음 오른쪽 셀로 이동
2. 현재는 권한란에 아무 숫자나 임의로 임력 가능 --> 권한을 기 입력된 1,2,3,4 중에 선택할 수 있도록 하여야 함.

**Comment by seungkwanwoo** [comment]
v0.1.11에 반영
