### ISSUE TITLE
기초정보 - 계정설정 - 계정정보

### ISSUE THREAD

**Issue by boazseong** [GiveYouMe/GymAccount#38]
기초정보 - 계정설정 - 계정정보

계정 정보 보이기 창 가로 넓게

MA
![0010-2](https://user-images.githubusercontent.com/80180034/110897291-86f0b680-8340-11eb-8a95-dd5125e2af32.PNG)

GA

![0010-1](https://user-images.githubusercontent.com/80180034/110897281-81936c00-8340-11eb-8f80-4ae2346ba913.PNG)

**Comment by seungkwanwoo** [comment]
v0.1.12에 반영
