### ISSUE TITLE
기초정보 - 계정설정 - 계정추가

### ISSUE THREAD

**Issue by boazseong** [GiveYouMe/GymAccount#39]
기초정보 - 계정설정 - 계정추가

분류 선택이 되지 않은 상태에서 [계정추가] 하면 분류를 먼저 선택하라는 팝업 안내가 나옴. 
그러나, 하위분류가 선택되지 않은 상태에서는 가장 위에 있는 하위분류 항목을 임으로 넣어 계정추가 상태가 됨. 
--> 하위분류가 선택되지 않은 상태에서 [계정추가}하면 "하위분류를 먼저 선택하세요" 안내 팝업 도출

추가하려는 계정의 분류, 하위분류를 먼저 결정한 후에에 [계정추가] 가능하도록 수정

**Comment by seungkwanwoo** [comment]
v0.1.12에 반영
