### ISSUE TITLE
후원자데이터창  보기

### ISSUE THREAD

**Issue by boazseong** [GiveYouMe/GymAccount#4]
후원자 창에서 
후원자가 지원하는 계정 등록 섹션의 필드명이 영문으로 나옴.
![1-0001](https://user-images.githubusercontent.com/80180034/110259317-67792700-7fea-11eb-81cf-93f0c02e2fc1.PNG)
![1-0002](https://user-images.githubusercontent.com/80180034/110259323-6a741780-7fea-11eb-90f6-96fd481f6c68.PNG)

**Comment by techcap** [comment]
v0.1.4에 수정되었습니다.
