### ISSUE TITLE
엑셀로 저장 - 저장위치

### ISSUE THREAD

**Issue by boazseong** [GiveYouMe/GymAccount#42]
엑셀로 저장

1. 저장 위치 : 프로그램 설치 폴더 아래 \ReportData\.. 이런 형식으로 하위 폴더 만들어 저장
MA 
![0013-2](https://user-images.githubusercontent.com/80180034/110899011-a9d09a00-8343-11eb-9e97-57c65df16abb.PNG)

GA 
![0013-1](https://user-images.githubusercontent.com/80180034/110899032-b654f280-8343-11eb-9ba3-7e1028271375.PNG)

--> 폴더 선택할 수 있도록 해야 할 듯함.

2. 실제 저장 여부 : 위 지정된 폴더에서 엑셀파일 찾을 수 없음.

**Comment by seungkwanwoo** [comment]
엑셀 저장 지원하지 않음
