### ISSUE TITLE
기초정보-계정정보-이메일 오타

### ISSUE THREAD

**Issue by boazseong** [GiveYouMe/GymAccount#45]
기초정보-계정정보-이메일 오타

계정 정보 섹션의 가장 아래 '이메일' 에서 '일'자 누락
![2-003-1](https://user-images.githubusercontent.com/80180034/112919212-9abe5a00-9141-11eb-95c4-7910d5fbf6c8.PNG)
![2-003-2](https://user-images.githubusercontent.com/80180034/112919214-9d20b400-9141-11eb-81dd-2b6e3291bf4c.PNG)

**Comment by seungkwanwoo** [comment]
v0.1.12에 반영
