### ISSUE TITLE
기초정보-계정정보 --> 공제관련 환경설정 1

### ISSUE THREAD

**Issue by boazseong** [GiveYouMe/GymAccount#47]
기초정보-계정정보 -->//  공제관련 환경설정 1) 오타부분

이 창에서 보이는 오타 혹은 누락 부분 종합

1.  공제명 --> 공제명 2 / 숫자 2 누락
![2-005-3](https://user-images.githubusercontent.com/80180034/112920196-6d72ab80-9143-11eb-8af4-a555c1bb2ad9.PNG)

2. Code찾 ---> Code찾기 / '기' 누락 , 혹은 감춰져서 안보이나?
![2-005-4](https://user-images.githubusercontent.com/80180034/112920245-87ac8980-9143-11eb-885a-279fd9031038.PNG)
여기 보이는 7개 외에도 보험회사 등록 및 변경 섹션에도 있으나, 이 부분은 비활성화할 것이므로 무시하였음.

3. 빨간 글씨 부분 뒷3글자 '택가능' 안보임 
![2-006-2](https://user-images.githubusercontent.com/80180034/112920367-c5111700-9143-11eb-900d-f1d9df248f1e.PNG)

4. 다음 그림의 뒷 1글자 "다." 안보임
![2-007-2](https://user-images.githubusercontent.com/80180034/112920428-e40fa900-9143-11eb-8556-a936039cb8c6.PNG)

**Comment by seungkwanwoo** [comment]
v0.1.12에 반영
