### ISSUE TITLE
기초정보-계정정보 -->// 공제관련 환경설정2

### ISSUE THREAD

**Issue by boazseong** [GiveYouMe/GymAccount#48]
기초정보-계정정보 -->// 공제관련 환경설정2

보험회사 등록 및 변경 섹션 전체 비활성화하기
![2-008-1](https://user-images.githubusercontent.com/80180034/112920677-64cea500-9144-11eb-8082-dc89b666ac73.PNG)

**Comment by seungkwanwoo** [comment]
v0.1.12에 반영
