### ISSUE TITLE
후원자 데이터 - 분류1 데이터 안보임

### ISSUE THREAD

**Issue by boazseong** [GiveYouMe/GymAccount#5]
후원자 데이터 - 분류1 데이터 안보임
![1-0003](https://user-images.githubusercontent.com/80180034/110259467-1584d100-7feb-11eb-8eb4-270c2289e0c5.PNG)
![1-0003-1](https://user-images.githubusercontent.com/80180034/110259469-16b5fe00-7feb-11eb-8cbb-5f35236c72e9.PNG)

**Comment by techcap** [comment]
v0.1.5에 반영

**Comment by boazseong** [comment]
확인!
