### ISSUE TITLE
기초정보-계정정보-엑셀로저장

### ISSUE THREAD

**Issue by boazseong** [GiveYouMe/GymAccount#51]
기초정보-계정정보-엑셀로저장

엑셀로 저장시 팝업 내용
![2-0011-1](https://user-images.githubusercontent.com/80180034/112921862-76b14780-9146-11eb-9aa6-b7b050eeda9a.PNG)

1. 저장위치를 "문서/GA-Report/기초정보"로 변경요청  --> 
기본 저장 위치가 프로그램 실행된 폴더에 Report폴더를 생성하고 그 아래에 큰 메뉴이름 폴더를 만들어 그 안에 파일을 생성하는 형태인데, 이 기본 저장 위치를 '문서/GA-Report'로 변경하기를 원함.

2. 팝업창에서 "예" 선택시 아무 작동없이 창 닫힘. --> 해당 폴더로 윈도우즈 탐색기창 열려 이동.

3. 해당 위치 이동후 실제 저장된 파일 -->엑셀파일 아님?
![2-0011-2](https://user-images.githubusercontent.com/80180034/112922210-0eaf3100-9147-11eb-8916-ccad84d2523a.PNG)

**Comment by seungkwanwoo** [comment]
엑셀 저장 지원하지 않음
