### ISSUE TITLE
기초정보-계좌/현금 - 계좌추가

### ISSUE THREAD

**Issue by boazseong** [GiveYouMe/GymAccount#57]
기초정보-계좌/현금 - 계좌추가

추가 계좌 정보 입력후 저장시

MA  : 
![1202-3](https://user-images.githubusercontent.com/80180034/121640282-b0001f00-cac8-11eb-8e73-a100d0a60e13.png)

GA : 
![1202-4](https://user-images.githubusercontent.com/80180034/121640314-b68e9680-cac8-11eb-8c1b-6df111ca9d72.png)

자세히 내용 --------------------------------------
이 대화 상자 대신 JIT(Just-in-time) 디버깅을 호출하는
방법에 대한 자세한 내용은 이 메시지의 뒷부분을 참조하십시오.

************** 예외 텍스트 **************
System.Data.OleDb.OleDbException (0x80040E14): INSERT INTO 문의 구문 오류입니다.
   위치: System.Data.OleDb.OleDbCommand.ExecuteCommandTextErrorHandling(OleDbHResult hr)
   위치: System.Data.OleDb.OleDbCommand.ExecuteCommandTextForSingleResult(tagDBPARAMS dbParams, Object& executeResult)
   위치: System.Data.OleDb.OleDbCommand.ExecuteCommandText(Object& executeResult)
   위치: System.Data.OleDb.OleDbCommand.ExecuteCommand(CommandBehavior behavior, Object& executeResult)
   위치: System.Data.OleDb.OleDbCommand.ExecuteReaderInternal(CommandBehavior behavior, String method)
   위치: System.Data.OleDb.OleDbCommand.ExecuteNonQuery()
   위치: GymAccount.Form_Bank_Acct.추가버튼_Click(Object eventSender, EventArgs eventArgs)
   위치: System.Windows.Forms.Control.OnClick(EventArgs e)
   위치: System.Windows.Forms.Button.OnClick(EventArgs e)
   위치: System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   위치: System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   위치: System.Windows.Forms.Control.WndProc(Message& m)
   위치: System.Windows.Forms.ButtonBase.WndProc(Message& m)
   위치: System.Windows.Forms.Button.WndProc(Message& m)
   위치: System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   위치: System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   위치: System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** 로드된 어셈블리 **************
mscorlib
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4341.0 built by: NET48REL1LAST_C
    코드베이스: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
System
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4300.0 built by: NET48REL1LAST_C
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
GymAccount
    어셈블리 버전: 0.1.9.0
    Win32 버전: 0.1.9.0
    코드베이스: file:///C:/Users/boazs/AppData/Local/Apps/2.0/HM9V0LOQ.GP8/WKYGCPK5.8TO/gyma..tion_50956945cd5a50b1_0000.0000_1b80d634ea92383f/GymAccount.exe
----------------------------------------
System.Windows.Forms
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4341.0 built by: NET48REL1LAST_C
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4084.0 built by: NET48REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4190.0 built by: NET48REL1LAST_B
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4341.0 built by: NET48REL1LAST_C
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4084.0 built by: NET48REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
TechlTemp
    어셈블리 버전: 1.0.0.0
    Win32 버전: 1.0.0.0
    코드베이스: file:///C:/Users/boazs/AppData/Local/Apps/2.0/HM9V0LOQ.GP8/WKYGCPK5.8TO/gyma..tion_50956945cd5a50b1_0000.0000_1b80d634ea92383f/TechlTemp.DLL
----------------------------------------
netstandard
    어셈블리 버전: 2.0.0.0
    Win32 버전: 4.8.4084.0
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
GymAccount.Common
    어셈블리 버전: 1.0.0.0
    Win32 버전: 1.0.0.0
    코드베이스: file:///C:/Users/boazs/AppData/Local/Apps/2.0/HM9V0LOQ.GP8/WKYGCPK5.8TO/gyma..tion_50956945cd5a50b1_0000.0000_1b80d634ea92383f/GymAccount.Common.DLL
----------------------------------------
UpgradeHelpers.Gui
    어셈블리 버전: 1.0.0.0
    Win32 버전: 1.0.0.0
    코드베이스: file:///C:/Users/boazs/AppData/Local/Apps/2.0/HM9V0LOQ.GP8/WKYGCPK5.8TO/gyma..tion_50956945cd5a50b1_0000.0000_1b80d634ea92383f/UpgradeHelpers.Gui.DLL
----------------------------------------
Microsoft.VisualBasic
    어셈블리 버전: 10.0.0.0
    Win32 버전: 14.8.4084.0 built by: NET48REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Windows.Forms.resources
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4084.0 built by: NET48REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ko_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
mscorlib.resources
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4084.0 built by: NET48REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_ko_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
UpgradeHelpers.DB.DAO
    어셈블리 버전: 1.0.0.0
    Win32 버전: 1.0.0.0
    코드베이스: file:///C:/Users/boazs/AppData/Local/Apps/2.0/HM9V0LOQ.GP8/WKYGCPK5.8TO/gyma..tion_50956945cd5a50b1_0000.0000_1b80d634ea92383f/UpgradeHelpers.DB.DAO.DLL
----------------------------------------
UpgradeHelpers.DB.Essentials
    어셈블리 버전: 1.0.0.0
    Win32 버전: 1.0.0.0
    코드베이스: file:///C:/Users/boazs/AppData/Local/Apps/2.0/HM9V0LOQ.GP8/WKYGCPK5.8TO/gyma..tion_50956945cd5a50b1_0000.0000_1b80d634ea92383f/UpgradeHelpers.DB.Essentials.DLL
----------------------------------------
System.Data
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4270.0 built by: NET48REL1LAST_C
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
FarPoint.Win.Spread
    어셈블리 버전: 11.40.20177.0
    Win32 버전: 11.40.20177.0
    코드베이스: file:///C:/Users/boazs/AppData/Local/Apps/2.0/HM9V0LOQ.GP8/WKYGCPK5.8TO/gyma..tion_50956945cd5a50b1_0000.0000_1b80d634ea92383f/FarPoint.Win.Spread.DLL
----------------------------------------
FarPoint.Win
    어셈블리 버전: 11.40.20177.0
    Win32 버전: 11.40.20177.0
    코드베이스: file:///C:/Users/boazs/AppData/Local/Apps/2.0/HM9V0LOQ.GP8/WKYGCPK5.8TO/gyma..tion_50956945cd5a50b1_0000.0000_1b80d634ea92383f/FarPoint.Win.DLL
----------------------------------------
GrapeCity.Spreadsheet.Win
    어셈블리 버전: 11.40.20177.0
    Win32 버전: 11.40.20177.0
    코드베이스: file:///C:/Users/boazs/AppData/Local/Apps/2.0/HM9V0LOQ.GP8/WKYGCPK5.8TO/gyma..tion_50956945cd5a50b1_0000.0000_1b80d634ea92383f/GrapeCity.Spreadsheet.Win.DLL
----------------------------------------
UpgradeHelpers.FpSpread
    어셈블리 버전: 1.0.0.0
    Win32 버전: 1.0.0.0
    코드베이스: file:///C:/Users/boazs/AppData/Local/Apps/2.0/HM9V0LOQ.GP8/WKYGCPK5.8TO/gyma..tion_50956945cd5a50b1_0000.0000_1b80d634ea92383f/UpgradeHelpers.FpSpread.DLL
----------------------------------------
UpgradeHelpers.DataGridViewFlex
    어셈블리 버전: 0.0.0.0
    Win32 버전: 0.0.0.0
    코드베이스: file:///C:/Users/boazs/AppData/Local/Apps/2.0/HM9V0LOQ.GP8/WKYGCPK5.8TO/gyma..tion_50956945cd5a50b1_0000.0000_1b80d634ea92383f/UpgradeHelpers.DataGridViewFlex.DLL
----------------------------------------
UpgradeHelpers.DataGridViewCommon
    어셈블리 버전: 1.0.0.0
    Win32 버전: 1.0.0.0
    코드베이스: file:///C:/Users/boazs/AppData/Local/Apps/2.0/HM9V0LOQ.GP8/WKYGCPK5.8TO/gyma..tion_50956945cd5a50b1_0000.0000_1b80d634ea92383f/UpgradeHelpers.DataGridViewCommon.DLL
----------------------------------------
UpgradeHelpers.Gui.Graphics
    어셈블리 버전: 1.0.0.0
    Win32 버전: 1.0.0.0
    코드베이스: file:///C:/Users/boazs/AppData/Local/Apps/2.0/HM9V0LOQ.GP8/WKYGCPK5.8TO/gyma..tion_50956945cd5a50b1_0000.0000_1b80d634ea92383f/UpgradeHelpers.Gui.Graphics.DLL
----------------------------------------
GrapeCity.Spreadsheet
    어셈블리 버전: 11.40.20177.0
    Win32 버전: 11.40.20177.0
    코드베이스: file:///C:/Users/boazs/AppData/Local/Apps/2.0/HM9V0LOQ.GP8/WKYGCPK5.8TO/gyma..tion_50956945cd5a50b1_0000.0000_1b80d634ea92383f/GrapeCity.Spreadsheet.DLL
----------------------------------------
GrapeCity.CalcEngine
    어셈블리 버전: 11.40.20177.0
    Win32 버전: 11.40.20177.0
    코드베이스: file:///C:/Users/boazs/AppData/Local/Apps/2.0/HM9V0LOQ.GP8/WKYGCPK5.8TO/gyma..tion_50956945cd5a50b1_0000.0000_1b80d634ea92383f/GrapeCity.CalcEngine.DLL
----------------------------------------
WindowsBase
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4341.0 built by: NET48REL1LAST_C
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
FarPoint.Excel
    어셈블리 버전: 11.40.20177.0
    Win32 버전: 11.40.20177.0
    코드베이스: file:///C:/Users/boazs/AppData/Local/Apps/2.0/HM9V0LOQ.GP8/WKYGCPK5.8TO/gyma..tion_50956945cd5a50b1_0000.0000_1b80d634ea92383f/FarPoint.Excel.DLL
----------------------------------------
FarPoint.Localization
    어셈블리 버전: 11.40.20177.0
    Win32 버전: 11.40.20177.0
    코드베이스: file:///C:/Users/boazs/AppData/Local/Apps/2.0/HM9V0LOQ.GP8/WKYGCPK5.8TO/gyma..tion_50956945cd5a50b1_0000.0000_1b80d634ea92383f/FarPoint.Localization.DLL
----------------------------------------
FarPoint.CalcEngine
    어셈블리 버전: 11.40.20177.0
    Win32 버전: 11.40.20177.0
    코드베이스: file:///C:/Users/boazs/AppData/Local/Apps/2.0/HM9V0LOQ.GP8/WKYGCPK5.8TO/gyma..tion_50956945cd5a50b1_0000.0000_1b80d634ea92383f/FarPoint.CalcEngine.DLL
----------------------------------------
System.Design
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4084.0 built by: NET48REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
FarPoint.Win.Chart
    어셈블리 버전: 11.40.20177.0
    Win32 버전: 11.40.20177.0
    코드베이스: file:///C:/Users/boazs/AppData/Local/Apps/2.0/HM9V0LOQ.GP8/WKYGCPK5.8TO/gyma..tion_50956945cd5a50b1_0000.0000_1b80d634ea92383f/FarPoint.Win.Chart.DLL
----------------------------------------
FarPoint.PluginCalendar.WinForms
    어셈블리 버전: 11.40.20177.0
    Win32 버전: 11.40.20177.0
    코드베이스: file:///C:/Users/boazs/AppData/Local/Apps/2.0/HM9V0LOQ.GP8/WKYGCPK5.8TO/gyma..tion_50956945cd5a50b1_0000.0000_1b80d634ea92383f/FarPoint.PluginCalendar.WinForms.DLL
----------------------------------------
System.Data.resources
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4084.0 built by: NET48REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Data.resources/v4.0_4.0.0.0_ko_b77a5c561934e089/System.Data.resources.dll
----------------------------------------
System.Transactions
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4084.0 built by: NET48REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.EnterpriseServices
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4084.0 built by: NET48REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
System.Numerics
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.8.4084.0 built by: NET48REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
UpgradeHelpers.Utils
    어셈블리 버전: 1.0.0.0
    Win32 버전: 1.0.0.0
    코드베이스: file:///C:/Users/boazs/AppData/Local/Apps/2.0/HM9V0LOQ.GP8/WKYGCPK5.8TO/gyma..tion_50956945cd5a50b1_0000.0000_1b80d634ea92383f/UpgradeHelpers.Utils.DLL
----------------------------------------

************** JIT 디버깅 **************
JIT(Just In Time) 디버깅을 사용하려면 이 응용 프로그램 또는 컴퓨터의
config 파일(machine.config)의 jitDebugging 값을 
system.windows.forms 섹션에 설정해야 합니다.
또한 응용 프로그램은 디버깅할 수 있도록 컴파일되어야
합니다.

예:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

JIT 디버깅을 사용하면 처리되지 않은 모든 예외는
이 대화 상자에서 처리되지 않고 컴퓨터에 등록된 JIT 
디버거에 보내집니다.

**Comment by seungkwanwoo** [comment]
v0.1.12에 반영

**Comment by boazseong** [comment]
![image](https://user-images.githubusercontent.com/80180034/196427040-e3a972a7-3f70-474c-8630-560977e68134.png)

이 팝업창에서 예 선택시는 정상 작동합니다. 

그러나, 아니오 선택시 화면에 변화가 없습니다. 그러나 저장은 작동을 합니다. 
따라서, 아니오 선택시 화변이 닫히고 저장이 완료되어 초기화된 화면으로 돌아가도록 해주십시오.

**Comment by seungkwanwoo** [comment]
아니오 선택 시 저장이 완료되고 화면을 갱신하도록 수정하였습니다. (v0.1.12)

**Comment by boazseong** [comment]
넵. 감사합니다.
