### ISSUE TITLE
후원자데이터- 정기간행물

### ISSUE THREAD

**Issue by boazseong** [GiveYouMe/GymAccount#6]
후원자데이터- 정기간행물
비용 부담 정보 안보임

아래 캡쳐 이미지는 동일 회원의 정보임.
![1-0004](https://user-images.githubusercontent.com/80180034/110259566-a065cb80-7feb-11eb-889b-dce87a70d305.PNG)
![1-0004-1](https://user-images.githubusercontent.com/80180034/110259567-a196f880-7feb-11eb-94ca-ceffc13198fc.PNG)

**Comment by techcap** [comment]
v0.1.5에서 수정

**Comment by boazseong** [comment]
확인!
