### ISSUE TITLE
후원자데이터 - 코드,후원자명

### ISSUE THREAD

**Issue by boazseong** [GiveYouMe/GymAccount#8]
후원자데이터 - 코드,후원자명
코드 | 후원자명 보기란의 후원자명 칼럼 보기 기본 길이 수정요청
![1-0006](https://user-images.githubusercontent.com/80180034/110260830-33edcb00-7ff1-11eb-90fe-c76f71630f80.PNG)
![1-0006-1](https://user-images.githubusercontent.com/80180034/110260833-351ef800-7ff1-11eb-99ba-66aafd710b82.PNG)

**Comment by techcap** [comment]
v0.1.5에 반영

**Comment by boazseong** [comment]
기존보다는 확장되었으나 한글로 4글자정도 더 보이는 것이 좋겠음.
