### ISSUE TITLE
후원자데이터-검색

### ISSUE THREAD

**Issue by boazseong** [GiveYouMe/GymAccount#9]
검색후 데이터 내용

1. 검색후 데이터 순서  : MA-코드순, GA-무작위

2. 검색후 데이터 보여주기 필드 : MA - 코드, 후원자명  / GA - 더 많은 필드

![1-0007](https://user-images.githubusercontent.com/80180034/110261114-369cf000-7ff2-11eb-836d-6d343735c9cf.PNG)
![1-0007-1](https://user-images.githubusercontent.com/80180034/110261116-37ce1d00-7ff2-11eb-8bf5-a4790712ed66.PNG)

**Comment by techcap** [comment]
v0.1.5기준으로 다시 확인 요청

**Comment by boazseong** [comment]
확인되었음! 새로운 버그 발견 -> 새로운 이슈로 처리하겠음.
